language: python
python:
  - "2.7"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libcmph-dev
install: 
- pip install -r requirements.txt --use-mirrors
- pip install -r web/requirements.txt --use-mirrors

script:  nosetests